// data.js: species, classes, backgrounds and class features (5.5e)
const AN = {
  Black: ["#3c3c48", "Acid"],
  Blue: ["#3f6fd0", "Lightning"],
  Brass: ["#c9a24a", "Fire"],
  Bronze: ["#b07a3a", "Lightning"],
  Copper: ["#c0682f", "Acid"],
  Gold: ["#e8b83a", "Fire"],
  Green: ["#4a9a52", "Poison"],
  Red: ["#c8372d", "Fire"],
  Silver: ["#b8c4d0", "Cold"],
  White: ["#e8eef2", "Cold"],
};
const GI = {
  Cloud: ["#9fc4e8", "Cloud’s Jaunt", "Bonus-action teleport 30 ft"],
  Fire: ["#e0793a", "Fire’s Burn", "Extra fire damage on hit"],
  Frost: ["#9fe0f0", "Frost’s Chill", "Cold damage + slow"],
  Hill: ["#8ab05a", "Hill’s Tumble", "Knock a Large foe prone"],
  Stone: ["#a0a0a8", "Stone’s Endurance", "Reaction to reduce damage"],
  Storm: ["#8a7ae0", "Storm’s Thunder", "Reaction thunder damage"],
};
const dr = Object.entries(AN).map(([n, [c, d]]) => ({
  n: n + " · " + d,
  v: { skin: c, snout: c + "", mark: null, eye: "#f3c26b" },
  r: d,
  d: `Your ancestry is ${n.toLowerCase()}: your Breath Weapon and damage resistance are ${d.toLowerCase()}.`,
}));
const SP = [
  {
    n: "Dragonborn",
    s: "Proud, scaled kin of dragons who carry a sliver of draconic power in their breath and blood.",
    z: "Medium",
    sp: 30,
    dv: 60,
    v: { hs: 2, horns: 2, horn: "#2a1a1a", robe: "#7a3a3a", ears: 0 },
    tr: [
      [
        "Breath Weapon",
        "Exhale a 15-ft cone or 30-ft line of your ancestry’s damage",
      ],
      ["Damage Resistance", "Resist your ancestry’s damage type"],
      ["Darkvision", "60 ft"],
      ["Draconic Flight", "Level 5: spectral wings for 10 minutes"],
    ],
    L: dr,
    lh: "Draconic Ancestry",
  },
  {
    n: "Dwarf",
    s: "Stout, enduring folk of the mountain halls, hard to move and harder to forget.",
    z: "Medium",
    sp: 30,
    dv: 120,
    r: "Poison",
    v: {
      skin: "#e8b890",
      hair: "#b0562a",
      beard: "#b0562a",
      robe: "#7a4a2a",
      eye: "#6a4a2a",
    },
    tr: [
      ["Dwarven Resilience", "Poison resistance, advantage vs. poisoned"],
      ["Dwarven Toughness", "+1 HP per level"],
      ["Stonecunning", "Tremorsense on stone (bonus action)"],
    ],
    L: [],
  },
  {
    n: "Elf",
    s: "Graceful, long-lived folk touched by the Feywild, who rest in trance instead of sleeping.",
    z: "Medium",
    sp: 30,
    dv: 60,
    v: { ears: 1, hs: 1, skin: "#f3d6bd" },
    tr: [
      ["Fey Ancestry", "Advantage vs. charmed"],
      ["Keen Senses", "Proficiency in Insight, Perception or Survival"],
      ["Trance", "Long rest in 4 hours"],
    ],
    lh: "Elven Lineage",
    L: [
      {
        n: "High Elf",
        v: { hair: "#e8dcb0", eye: "#4a8ae0", robe: "#4a6ab0" },
        d: "Arcane schooling in your blood.",
        x: [
          ["Prestidigitation", "Cantrip (swappable on long rest)"],
          ["Detect Magic", "Level 3"],
          ["Misty Step", "Level 5"],
        ],
      },
      {
        n: "Wood Elf",
        sp: 35,
        v: {
          hair: "#6a4a22",
          eye: "#4aa04a",
          robe: "#4a7a3a",
          skin: "#e6bf94",
        },
        d: "Swift of foot and wise in the wild.",
        x: [
          ["Speed 35 ft", "Faster than other elves"],
          ["Druidcraft", "Cantrip"],
          ["Longstrider", "Level 3"],
          ["Pass without Trace", "Level 5"],
        ],
      },
      {
        n: "Drow",
        dv: 120,
        v: {
          skin: "#8a7fa8",
          hair: "#f2f2f2",
          eye: "#e04a5a",
          ears: 2,
          robe: "#3a2a5a",
        },
        d: "Underdark heritage and shadowy magic.",
        x: [
          ["Darkvision 120 ft", "Superior sight in the dark"],
          ["Dancing Lights", "Cantrip"],
          ["Faerie Fire", "Level 3"],
          ["Darkness", "Level 5"],
        ],
      },
    ],
  },
  {
    n: "Gnome",
    s: "Small, endlessly curious tinkerers and illusionists with bottomless enthusiasm.",
    z: "Small",
    sp: 30,
    dv: 60,
    v: {
      ears: 1,
      hat: "#c0392b",
      beard: "#f2f2f2",
      skin: "#f0b898",
      robe: "#3a6a7a",
      eye: "#5a3a8a",
    },
    tr: [["Gnomish Cunning", "Advantage on INT, WIS, CHA saves"]],
    lh: "Gnomish Lineage",
    L: [
      {
        n: "Forest Gnome",
        v: { robe: "#4a7a3a", hat: "#4a8a3a" },
        d: "Friend to small creatures.",
        x: [
          ["Minor Illusion", "Cantrip"],
          ["Speak with Animals", "Cast freely (prof. bonus/day)"],
        ],
      },
      {
        n: "Rock Gnome",
        v: { robe: "#7a6a5a", hat: "#c0392b" },
        d: "A natural inventor.",
        x: [
          ["Mending", "Cantrip"],
          ["Prestidigitation", "Cantrip"],
          ["Clockwork Device", "Craft tiny gadgets"],
        ],
      },
    ],
  },
  {
    n: "Goliath",
    s: "Towering mountain wanderers who carry the blessing of the giants.",
    z: "Medium",
    sp: 35,
    dv: 0,
    v: {
      skin: "#a9b4c0",
      hs: 2,
      eye: "#4a6a8a",
      robe: "#5a5a6a",
      mark: "#3a4a5a",
    },
    tr: [
      ["Powerful Build", "Count as larger for carrying"],
      ["Large Form", "Level 5: grow to Large for 10 min"],
    ],
    lh: "Giant Ancestry",
    L: Object.entries(GI).map(([n, [c, t, d]]) => ({
      n: n + " Giant",
      v: { mark: c },
      x: [[t, d]],
      d: "Descended from " + n.toLowerCase() + " giants.",
    })),
  },
  {
    n: "Halfling",
    s: "Small, cheerful and uncannily lucky, with a deep love of hearth and home.",
    z: "Small",
    sp: 30,
    dv: 0,
    v: {
      hs: 3,
      hair: "#7a4a22",
      skin: "#f0c8a0",
      robe: "#5a7a3a",
      eye: "#6a4a22",
    },
    tr: [
      ["Brave", "Advantage vs. frightened"],
      ["Halfling Nimbleness", "Move through larger creatures"],
      ["Luck", "Reroll a 1 on a d20"],
      ["Naturally Stealthy", "Hide behind larger creatures"],
    ],
    L: [],
  },
  {
    n: "Human",
    s: "Ambitious and adaptable, humans thrive anywhere there is a quest to chase.",
    z: "Medium or Small",
    sp: 30,
    dv: 0,
    v: { skin: "#e0b08a", hair: "#3a2a1a", robe: "#8a5a3a", eye: "#5a3a22" },
    tr: [
      ["Resourceful", "Heroic Inspiration each long rest"],
      ["Skillful", "One extra skill proficiency"],
      ["Versatile", "One Origin feat of your choice"],
    ],
    L: [],
  },
  {
    n: "Orc",
    s: "Driven by relentless vitality, orcs push on long after others would fall.",
    z: "Medium",
    sp: 30,
    dv: 120,
    v: {
      skin: "#7aa05a",
      hair: "#1a1a1a",
      tusk: 1,
      ears: 1,
      robe: "#5a3a2a",
      eye: "#d0a02a",
    },
    tr: [
      ["Adrenaline Rush", "Dash as a bonus action, gain temp HP"],
      ["Relentless Endurance", "Drop to 1 HP instead of 0, once per long rest"],
    ],
    L: [],
  },
  {
    n: "Tiefling",
    s: "Bearers of an otherworldly legacy, shaped by the planes of the lower realms.",
    z: "Medium or Small",
    sp: 30,
    dv: 60,
    v: { horns: 2, skin: "#b04a5a", hair: "#2a1a2a", robe: "#4a2a4a" },
    tr: [
      ["Otherworldly Presence", "Thaumaturgy cantrip"],
      ["Darkvision", "60 ft"],
    ],
    lh: "Fiendish Legacy",
    L: [
      {
        n: "Abyssal",
        r: "Poison",
        v: { skin: "#5a9a8a", horns: 3, eye: "#8ae04a", horn: "#2a3a3a" },
        d: "Chaos of the Abyss.",
        x: [
          ["Poison Resistance", ""],
          ["Poison Spray", "Cantrip"],
          ["Ray of Sickness", "Level 3"],
          ["Hold Person", "Level 5"],
        ],
      },
      {
        n: "Chthonic",
        r: "Necrotic",
        v: { skin: "#9a8aa8", horns: 1, eye: "#a04ae0", horn: "#3a2a4a" },
        d: "The cold touch of the underworld.",
        x: [
          ["Necrotic Resistance", ""],
          ["Chill Touch", "Cantrip"],
          ["False Life", "Level 3"],
          ["Ray of Enfeeblement", "Level 5"],
        ],
      },
      {
        n: "Infernal",
        r: "Fire",
        v: { skin: "#c0453a", horns: 2, eye: "#f3c26b" },
        d: "Blood of the Nine Hells.",
        x: [
          ["Fire Resistance", ""],
          ["Fire Bolt", "Cantrip"],
          ["Hellish Rebuke", "Level 3"],
          ["Darkness", "Level 5"],
        ],
      },
    ],
  },
];
const CL = [
  [
    "Barbarian",
    "🪓",
    "Rage-fueled warrior who shrugs off blows.",
    ["STR", "CON"],
    "d12 · Frontline",
    "#a04a3a",
  ],
  [
    "Bard",
    "🪕",
    "Charismatic performer whose songs charm and inspire.",
    ["CHA", "DEX"],
    "d8 · Support",
    "#b05a8a",
  ],
  [
    "Cleric",
    "🔔",
    "Divine channel who heals allies and smites foes.",
    ["WIS", "CON"],
    "d8 · Healer",
    "#d8c08a",
  ],
  [
    "Druid",
    "🌿",
    "Keeper of the wild who shapeshifts and commands nature.",
    ["WIS", "CON"],
    "d8 · Controller",
    "#4a7a3a",
  ],
  [
    "Fighter",
    "⚔️",
    "Master of arms and armor, reliable in any fight.",
    ["STR", "CON"],
    "d10 · Frontline",
    "#6a7a8a",
  ],
  [
    "Monk",
    "🥋",
    "Swift martial artist channeling ki.",
    ["DEX", "WIS"],
    "d8 · Skirmisher",
    "#c08a3a",
  ],
  [
    "Paladin",
    "🛡️",
    "Sworn knight with radiant strikes and protection.",
    ["STR", "CHA"],
    "d10 · Defender",
    "#c0a050",
  ],
  [
    "Ranger",
    "🏹",
    "Wilderness hunter, deadly at range.",
    ["DEX", "WIS"],
    "d10 · Striker",
    "#3a6a4a",
  ],
  [
    "Rogue",
    "🗝️",
    "Shadowy trickster landing precise strikes.",
    ["DEX", "INT"],
    "d8 · Striker",
    "#3a3a4a",
  ],
  [
    "Sorcerer",
    "🔥",
    "Raw magic in the blood, bent by will.",
    ["CHA", "CON"],
    "d6 · Blaster",
    "#a03a5a",
  ],
  [
    "Warlock",
    "🌙",
    "Pact-bound caster empowered by a patron.",
    ["CHA", "CON"],
    "d8 · Blaster",
    "#4a2a6a",
  ],
  [
    "Wizard",
    "📖",
    "Scholar of the arcane with the widest spellbook.",
    ["INT", "CON"],
    "d6 · Controller",
    "#3a4a9a",
  ],
];
const ST = [
    "Species",
    "Background",
    "Class",
    "Skills",
    "Spells",
    "Ability Score",
    "Equipment",
    "Summary",
  ],
  CAS = [
    "Bard",
    "Cleric",
    "Druid",
    "Paladin",
    "Ranger",
    "Sorcerer",
    "Warlock",
    "Wizard",
  ];
const BG = [
  [
    "Acolyte",
    "🕯️",
    "Raised in service to a temple and its gods.",
    ["INT", "WIS", "CHA"],
    "Magic Initiate (Cleric)",
    ["Insight", "Religion"],
    "Calligrapher’s Supplies",
  ],
  [
    "Artisan",
    "🔨",
    "A skilled maker who learned a trade in a guild.",
    ["STR", "DEX", "INT"],
    "Crafter",
    ["Investigation", "Persuasion"],
    "One Artisan’s Tools",
  ],
  [
    "Charlatan",
    "🎭",
    "A smooth talker who lives by clever lies.",
    ["DEX", "CON", "CHA"],
    "Skilled",
    ["Deception", "Sleight of Hand"],
    "Forgery Kit",
  ],
  [
    "Criminal",
    "🗝️",
    "A thief or smuggler at home in the shadows.",
    ["DEX", "CON", "INT"],
    "Alert",
    ["Sleight of Hand", "Stealth"],
    "Thieves’ Tools",
  ],
  [
    "Entertainer",
    "🎻",
    "A performer who thrives in front of a crowd.",
    ["STR", "DEX", "CHA"],
    "Musician",
    ["Acrobatics", "Performance"],
    "One Musical Instrument",
  ],
  [
    "Farmer",
    "🌾",
    "Tough, patient and close to the land.",
    ["STR", "CON", "WIS"],
    "Tough",
    ["Animal Handling", "Nature"],
    "Carpenter’s Tools",
  ],
  [
    "Guard",
    "🗼",
    "Trained to keep watch and protect others.",
    ["STR", "INT", "WIS"],
    "Alert",
    ["Athletics", "Perception"],
    "One Gaming Set",
  ],
  [
    "Guide",
    "🧭",
    "A wilderness scout who leads travelers safely.",
    ["DEX", "CON", "WIS"],
    "Magic Initiate (Druid)",
    ["Stealth", "Survival"],
    "Cartographer’s Tools",
  ],
  [
    "Hermit",
    "🏕️",
    "Lived in seclusion, seeking quiet insight.",
    ["CON", "WIS", "CHA"],
    "Healer",
    ["Medicine", "Religion"],
    "Herbalism Kit",
  ],
  [
    "Merchant",
    "💰",
    "A trader with a keen nose for a deal.",
    ["CON", "INT", "CHA"],
    "Lucky",
    ["Animal Handling", "Persuasion"],
    "Navigator’s Tools",
  ],
  [
    "Noble",
    "👑",
    "Born to privilege, title and expectation.",
    ["STR", "INT", "CHA"],
    "Skilled",
    ["History", "Persuasion"],
    "One Gaming Set",
  ],
  [
    "Sage",
    "📚",
    "A scholar steeped in books and lore.",
    ["CON", "INT", "WIS"],
    "Magic Initiate (Wizard)",
    ["Arcana", "History"],
    "Calligrapher’s Supplies",
  ],
  [
    "Sailor",
    "⚓",
    "Weathered by the sea and the ship’s crew.",
    ["STR", "DEX", "WIS"],
    "Tavern Brawler",
    ["Acrobatics", "Perception"],
    "Navigator’s Tools",
  ],
  [
    "Scribe",
    "🪶",
    "A careful writer and keeper of records.",
    ["DEX", "INT", "WIS"],
    "Skilled",
    ["Investigation", "Perception"],
    "Calligrapher’s Supplies",
  ],
  [
    "Soldier",
    "🎖️",
    "Trained in war and the discipline of arms.",
    ["STR", "DEX", "CON"],
    "Savage Attacker",
    ["Athletics", "Intimidation"],
    "One Gaming Set",
  ],
  [
    "Wayfarer",
    "🥾",
    "A drifter who survived on the open road.",
    ["DEX", "WIS", "CHA"],
    "Lucky",
    ["Insight", "Stealth"],
    "Thieves’ Tools",
  ],
];
const F = {
  Barbarian: [
    [1, "😡", "Rage", "Resist weapon damage and hit harder in melee."],
    [1, "🛡️", "Unarmored Defense", "AC is 10 + DEX + CON without armor."],
    [
      2,
      "💢",
      "Reckless Attack",
      "Advantage on your STR attacks; foes gain it too.",
    ],
    [3, "🌟", "Subclass", "Choose a Primal Path."],
    [5, "⚡", "Extra Attack", "Attack twice per Attack action."],
  ],
  Bard: [
    [1, "🎶", "Bardic Inspiration", "Give an ally a d6 to add to a roll."],
    [1, "✨", "Spellcasting", "Cast bard spells using Charisma."],
    [
      2,
      "🃏",
      "Jack of All Trades",
      "Add half proficiency to unproficient checks.",
    ],
    [3, "🌟", "Subclass", "Choose a Bard College."],
    [
      5,
      "🎵",
      "Font of Inspiration",
      "Regain Inspiration on a short rest; die becomes d8.",
    ],
  ],
  Cleric: [
    [1, "✨", "Spellcasting", "Prepare and cast cleric spells with Wisdom."],
    [1, "⚖️", "Divine Order", "Choose Protector or Thaumaturge."],
    [2, "☀️", "Channel Divinity", "Divine Spark or Turn Undead."],
    [3, "🌟", "Subclass", "Choose a Divine Domain."],
    [5, "🔥", "Sear Undead", "Turning undead also deals radiant damage."],
  ],
  Druid: [
    [1, "🌿", "Spellcasting", "Cast druid spells using Wisdom."],
    [1, "🌲", "Primal Order", "Choose Magician or Warden."],
    [2, "🐻", "Wild Shape", "Transform into a beast you have seen."],
    [2, "🐾", "Wild Companion", "Spend Wild Shape to summon a fey familiar."],
    [3, "🌟", "Subclass", "Choose a Druid Circle."],
    [5, "🌱", "Wild Resurgence", "Trade spell slots and Wild Shape uses."],
  ],
  Fighter: [
    [1, "🥊", "Fighting Style", "Gain a fighting-style feat."],
    [1, "💚", "Second Wind", "Bonus action: regain d10 + level HP."],
    [2, "⏱️", "Action Surge", "Take one extra action on your turn."],
    [3, "🌟", "Subclass", "Choose a Martial Archetype."],
    [5, "⚡", "Extra Attack", "Attack twice per Attack action."],
  ],
  Monk: [
    [
      1,
      "👊",
      "Martial Arts",
      "Fight with DEX, d6 unarmed strikes and a bonus strike.",
    ],
    [
      2,
      "☯️",
      "Monk’s Focus",
      "Spend Focus Points on Flurry, Patient Defense and Step of the Wind.",
    ],
    [3, "🌀", "Deflect Attacks", "Reaction to reduce weapon damage."],
    [3, "🌟", "Subclass", "Choose a Monk Subclass."],
    [5, "💫", "Stunning Strike", "Spend Focus to stun a creature you hit."],
  ],
  Paladin: [
    [1, "🙌", "Lay On Hands", "Healing pool equal to 5 × level."],
    [1, "✨", "Spellcasting", "Prepare paladin spells with Charisma."],
    [2, "💥", "Paladin’s Smite", "Cast Divine Smite free once per long rest."],
    [3, "☀️", "Channel Divinity", "Divine Sense and subclass options."],
    [5, "🐎", "Faithful Steed", "Summon a steed once per long rest."],
  ],
  Ranger: [
    [1, "🎯", "Favored Enemy", "Cast Hunter’s Mark free, twice per rest."],
    [1, "✨", "Spellcasting", "Cast ranger spells using Wisdom."],
    [2, "🧭", "Deft Explorer", "Gain Expertise and extra languages."],
    [3, "🌟", "Subclass", "Choose a Ranger Conclave."],
    [5, "⚡", "Extra Attack", "Attack twice per Attack action."],
  ],
  Rogue: [
    [
      1,
      "🗡️",
      "Sneak Attack",
      "Extra 1d6 damage with advantage or an ally nearby.",
    ],
    [1, "🔓", "Thieves’ Cant", "Secret rogue language and signs."],
    [2, "💨", "Cunning Action", "Bonus action to Dash, Disengage or Hide."],
    [3, "🌟", "Subclass", "Choose a Roguish Archetype."],
    [5, "🌫️", "Uncanny Dodge", "Reaction to halve an attack’s damage."],
  ],
  Sorcerer: [
    [
      1,
      "🔮",
      "Innate Sorcery",
      "Bonus action: boost spell DCs and gain advantage.",
    ],
    [1, "✨", "Spellcasting", "Cast sorcerer spells using Charisma."],
    [2, "🪙", "Font of Magic", "Trade Sorcery Points for spell slots."],
    [2, "🌀", "Metamagic", "Twist your spells in unusual ways."],
    [3, "🌟", "Subclass", "Choose a Sorcerous Origin."],
  ],
  Warlock: [
    [1, "📜", "Eldritch Invocations", "Customize with a magical invocation."],
    [1, "🌙", "Pact Magic", "Few slots that refresh on short rests."],
    [2, "🎩", "Magical Cunning", "Regain slots by performing a ritual."],
    [3, "🌟", "Subclass", "Choose your Otherworldly Patron."],
  ],
  Wizard: [
    [1, "📖", "Spellcasting", "Keep a spellbook of wizard spells."],
    [1, "🔁", "Arcane Recovery", "Regain spell slots on a short rest."],
    [2, "🎓", "Scholar", "Expertise in a knowledge skill."],
    [3, "🌟", "Subclass", "Choose a Wizard School."],
    [5, "🧠", "Memorize Spell", "Swap a prepared spell on a short rest."],
  ],
};
const SF = (n) => [
    n,
    "🌟",
    "Subclass Feature",
    "A new feature from your subclass.",
  ],
  MORE = {
    Barbarian: [
      SF(6),
      [
        7,
        "🐺",
        "Feral Instinct",
        "Advantage on initiative; act while surprised if you Rage.",
      ],
      [
        9,
        "💪",
        "Brutal Strike",
        "Forgo advantage for +1d10 damage and a rider effect.",
      ],
      SF(10),
      [
        11,
        "🔥",
        "Relentless Rage",
        "Stay up with a CON-based HP total instead of dropping.",
      ],
    ],
    Bard: [
      SF(6),
      [7, "🔇", "Countercharm", "Inspire allies to resist fear and charm."],
      [9, "🎓", "Expertise", "Two more Expertise skills."],
      [10, "📚", "Magical Secrets", "Learn spells from any class list."],
    ],
    Cleric: [
      SF(6),
      [
        7,
        "🙏",
        "Blessed Strikes",
        "Add 1d8 radiant damage to weapon hits or cantrips.",
      ],
      [
        10,
        "🕊️",
        "Divine Intervention",
        "Call on your god to cast a cleric spell for free.",
      ],
    ],
    Druid: [
      SF(6),
      [
        7,
        "🌪️",
        "Elemental Fury",
        "Add elemental damage to attacks or cantrips.",
      ],
    ],
    Fighter: [
      [6, "📈", "Extra Feat", "A bonus Ability Score Improvement."],
      SF(7),
      [9, "🛡️", "Indomitable", "Reroll a failed saving throw."],
      [9, "🧠", "Tactical Master", "Swap a weapon’s mastery property."],
      [11, "⚡", "Two Extra Attacks", "Attack three times per Attack action."],
    ],
    Monk: [
      SF(6),
      [6, "💥", "Empowered Strikes", "Unarmed strikes can deal force damage."],
      [7, "💨", "Evasion", "No damage on a successful DEX save."],
      [9, "🧗", "Acrobatic Movement", "Run along walls and across water."],
      [
        10,
        "🧘",
        "Heightened Focus",
        "Boost Flurry, Patient Defense and Step of the Wind.",
      ],
      SF(11),
    ],
    Paladin: [
      [
        6,
        "🔰",
        "Aura of Protection",
        "You and nearby allies add CHA to saves.",
      ],
      SF(7),
      [9, "🚫", "Abjure Foes", "Frighten foes with Channel Divinity."],
      [
        10,
        "🦁",
        "Aura of Courage",
        "You and nearby allies can’t be frightened.",
      ],
      [
        11,
        "☀️",
        "Radiant Strikes",
        "Melee hits deal an extra 1d8 radiant damage.",
      ],
    ],
    Ranger: [
      [6, "🏃", "Roving", "+10 speed plus climb and swim speeds."],
      SF(7),
      [9, "🎓", "Expertise", "Two more Expertise skills."],
      [10, "🌄", "Tireless", "Temp HP and relief from exhaustion."],
      SF(11),
    ],
    Rogue: [
      [6, "🎓", "Expertise", "Two more Expertise skills."],
      [7, "🤸", "Evasion", "No damage on a successful DEX save."],
      [
        7,
        "🎲",
        "Reliable Talent",
        "Treat a 9 or lower as 10 on proficient checks.",
      ],
      SF(9),
      [
        11,
        "🎯",
        "Improved Cunning Strike",
        "Apply two Cunning Strike effects.",
      ],
    ],
    Sorcerer: [
      SF(6),
      [
        7,
        "🔥",
        "Sorcery Incarnate",
        "Boost Innate Sorcery with extra Metamagic.",
      ],
    ],
    Warlock: [
      SF(6),
      [9, "🤝", "Contact Patron", "Cast Contact Other Plane freely."],
      SF(10),
      [11, "🔮", "Mystic Arcanum", "A 6th-level spell once per long rest."],
    ],
    Wizard: [SF(6), SF(10)],
  };
for (const k in MORE) F[k].push(...MORE[k]);
Object.values(F).forEach((a) => a.sort((x, y) => x[0] - y[0]));
// Skills: [name, ability, used when…]
const SKL = [
  ["Acrobatics", "DEX", "Keeping your balance, tumbling, slipping free of a grab."],
  ["Animal Handling", "WIS", "Calming a horse, reading a guard dog's mood."],
  ["Arcana", "INT", "Recognizing spells, runes and magic items."],
  ["Athletics", "STR", "Climbing, swimming, jumping, shoving a foe."],
  ["Deception", "CHA", "Lying convincingly, bluffing, disguises."],
  ["History", "INT", "Recalling lore about kingdoms, wars and legends."],
  ["Insight", "WIS", "Telling whether someone is lying to you."],
  ["Intimidation", "CHA", "Scaring someone into backing down or talking."],
  ["Investigation", "INT", "Searching a room, finding clues, spotting how a trap works."],
  ["Medicine", "WIS", "Stabilizing a dying ally, diagnosing illness."],
  ["Nature", "INT", "Knowing plants, beasts, weather and terrain."],
  ["Perception", "WIS", "Noticing ambushes, hidden doors and traps. Used constantly."],
  ["Performance", "CHA", "Music, dance, acting, storytelling for a crowd."],
  ["Persuasion", "CHA", "Talking someone into helping you, haggling."],
  ["Religion", "INT", "Knowing gods, rites, holy symbols and undead."],
  ["Sleight of Hand", "DEX", "Picking pockets, palming objects."],
  ["Stealth", "DEX", "Sneaking past guards, hiding, ambushing."],
  ["Survival", "WIS", "Tracking, hunting, finding your way in the wild."],
];
// Class skills: [how many, choose from (empty = any), recommended]
const CSK = {
  Barbarian: [2, ["Animal Handling", "Athletics", "Intimidation", "Nature", "Perception", "Survival"], ["Athletics", "Perception"]],
  Bard: [3, [], ["Persuasion", "Deception", "Perception"]],
  Cleric: [2, ["History", "Insight", "Medicine", "Persuasion", "Religion"], ["Insight", "Medicine"]],
  Druid: [2, ["Arcana", "Animal Handling", "Insight", "Medicine", "Nature", "Perception", "Religion", "Survival"], ["Perception", "Nature"]],
  Fighter: [2, ["Acrobatics", "Animal Handling", "Athletics", "History", "Insight", "Intimidation", "Persuasion", "Perception", "Survival"], ["Athletics", "Perception"]],
  Monk: [2, ["Acrobatics", "Athletics", "History", "Insight", "Religion", "Stealth"], ["Acrobatics", "Stealth"]],
  Paladin: [2, ["Athletics", "Insight", "Intimidation", "Medicine", "Persuasion", "Religion"], ["Athletics", "Persuasion"]],
  Ranger: [3, ["Animal Handling", "Athletics", "Insight", "Investigation", "Nature", "Perception", "Stealth", "Survival"], ["Perception", "Stealth", "Survival"]],
  Rogue: [4, ["Acrobatics", "Athletics", "Deception", "Insight", "Intimidation", "Investigation", "Perception", "Persuasion", "Sleight of Hand", "Stealth"], ["Stealth", "Perception", "Acrobatics", "Investigation"]],
  Sorcerer: [2, ["Arcana", "Deception", "Insight", "Intimidation", "Persuasion", "Religion"], ["Arcana", "Persuasion"]],
  Warlock: [2, ["Arcana", "Deception", "History", "Intimidation", "Investigation", "Nature", "Religion"], ["Arcana", "Deception"]],
  Wizard: [2, ["Arcana", "History", "Insight", "Investigation", "Medicine", "Nature", "Religion"], ["Arcana", "Investigation"]],
};
// Class details for the summary: [saving throws, spellcasting ability, your first fight]
const CX = {
  Barbarian: [["STR", "CON"], "", "Rage as a bonus action, then run at the biggest enemy and swing your greataxe. Rage halves weapon damage against you, so you can stand in the middle of the fight."],
  Bard: [["DEX", "CHA"], "CHA", "Hang back. Give an ally Bardic Inspiration as a bonus action, then throw Vicious Mockery or Dissonant Whispers. Keep Healing Word for anyone who drops to 0 HP."],
  Cleric: [["WIS", "CHA"], "WIS", "Cast Bless on the party at the start, then stay near your friends. Use Sacred Flame or your mace, and Healing Word anyone who goes down."],
  Druid: [["INT", "WIS"], "WIS", "Open with Entangle or Faerie Fire to lock enemies down, then use your cantrips. From level 2, Wild Shape lets you turn into a beast and take hits."],
  Fighter: [["STR", "CON"], "", "Stand between the enemies and your squishier friends and attack every turn. Second Wind heals you when you're hurt; Action Surge at level 2 gives you a whole extra turn."],
  Monk: [["STR", "DEX"], "", "Dash in, attack with your weapon, then make a bonus unarmed strike. Your speed lets you reach enemy archers and spellcasters that others can't."],
  Paladin: [["WIS", "CHA"], "CHA", "Wade in with sword and shield and strike. Save Lay On Hands for emergencies; from level 2, spend a spell slot on a hit to smite for big radiant damage."],
  Ranger: [["STR", "DEX"], "WIS", "Cast Hunter's Mark on one enemy as a bonus action, then shoot it with your longbow every turn. Move the mark when it dies."],
  Rogue: [["DEX", "INT"], "", "Hide or attack an enemy that an ally is next to, so you get Sneak Attack. Hit once with a shortsword or shortbow, then use Cunning Action to step out of reach."],
  Sorcerer: [["CON", "CHA"], "CHA", "Stay at range and cast Fire Bolt every turn. Use Magic Missile when you need a sure hit, and keep Shield ready as a reaction if something reaches you."],
  Warlock: [["WIS", "CHA"], "CHA", "Cast Hex on a target as a bonus action, then Eldritch Blast it every turn. Your spell slots come back after a short rest, so don't hoard them."],
  Wizard: [["INT", "WIS"], "INT", "Stay behind the front line. Cast Fire Bolt or Ray of Frost, use Thunderwave if enemies get close, and Shield when an attack would hit you."],
};
// Starting equipment: kits [label, items, armor, weapons, gold]; g = gold-only option.
// armor: [base AC, DEX cap, shield bonus] or "UB" (10+DEX+CON) / "UM" (10+DEX+WIS)
// weapon: [name, damage, type, ability: S / D / F (finesse, best of STR or DEX)]
const EQ = {
  Barbarian: { g: 75, k: [["Standard kit", "Greataxe, 4 Handaxes, Explorer's Pack", "UB", [["Greataxe", "1d12", "slashing", "S"], ["Handaxe (thrown 20 ft)", "1d6", "slashing", "S"]], 15]] },
  Bard: { g: 90, k: [["Standard kit", "Leather Armor, 2 Daggers, Musical Instrument, Entertainer's Pack", [11, 99, 0], [["Dagger", "1d4", "piercing", "F"]], 19]] },
  Cleric: { g: 110, k: [["Standard kit", "Chain Shirt, Shield, Mace, Holy Symbol, Priest's Pack", [13, 2, 2], [["Mace", "1d6", "bludgeoning", "S"]], 7]] },
  Druid: { g: 50, k: [["Standard kit", "Leather Armor, Shield, Sickle, Quarterstaff (druidic focus), Explorer's Pack, Herbalism Kit", [11, 99, 2], [["Sickle", "1d4", "slashing", "S"], ["Quarterstaff", "1d6", "bludgeoning", "S"]], 9]] },
  Fighter: { g: 155, k: [["Heavy kit (melee)", "Chain Mail, Greatsword, Flail, 8 Javelins, Dungeoneer's Pack", [16, 0, 0], [["Greatsword", "2d6", "slashing", "S"], ["Javelin (thrown 30 ft)", "1d6", "piercing", "S"]], 4], ["Light kit (archer)", "Studded Leather, Scimitar, Shortsword, Longbow, 20 Arrows, Quiver, Dungeoneer's Pack", [12, 99, 0], [["Longbow (150 ft)", "1d8", "piercing", "D"], ["Scimitar", "1d6", "slashing", "F"]], 11]] },
  Monk: { g: 50, k: [["Standard kit", "Spear, 5 Daggers, Artisan's Tools, Explorer's Pack", "UM", [["Unarmed Strike", "1d6", "bludgeoning", "F"], ["Spear", "1d6", "piercing", "F"]], 11]] },
  Paladin: { g: 150, k: [["Standard kit", "Chain Mail, Shield, Longsword, 6 Javelins, Holy Symbol, Priest's Pack", [16, 0, 2], [["Longsword", "1d8", "slashing", "S"], ["Javelin (thrown 30 ft)", "1d6", "piercing", "S"]], 9]] },
  Ranger: { g: 150, k: [["Standard kit", "Studded Leather, Scimitar, Shortsword, Longbow, 20 Arrows, Quiver, Druidic Focus, Explorer's Pack", [12, 99, 0], [["Longbow (150 ft)", "1d8", "piercing", "D"], ["Scimitar", "1d6", "slashing", "F"]], 7]] },
  Rogue: { g: 100, k: [["Standard kit", "Leather Armor, 2 Daggers, Shortsword, Shortbow, 20 Arrows, Quiver, Thieves' Tools, Burglar's Pack", [11, 99, 0], [["Shortsword", "1d6", "piercing", "F"], ["Shortbow (80 ft)", "1d6", "piercing", "D"]], 8]] },
  Sorcerer: { g: 50, k: [["Standard kit", "Spear, 2 Daggers, Arcane Focus (crystal), Dungeoneer's Pack", [10, 99, 0], [["Dagger", "1d4", "piercing", "F"]], 28]] },
  Warlock: { g: 100, k: [["Standard kit", "Leather Armor, Sickle, 2 Daggers, Arcane Focus (orb), Book, Scholar's Pack", [11, 99, 0], [["Dagger", "1d4", "piercing", "F"]], 15]] },
  Wizard: { g: 55, k: [["Standard kit", "2 Daggers, Quarterstaff (arcane focus), Robe, Spellbook, Scholar's Pack", [10, 99, 0], [["Quarterstaff", "1d6", "bludgeoning", "S"]], 5]] },
};
// Plain-language help for rules terms (shown behind a "?")
const GL = {
  Speed: "How many feet you can move on your turn. 30 ft is about 6 squares on a battle map.",
  Darkvision: "You can see in dim light as if it were bright, and in darkness as if it were dim, out to this range.",
  Resist: "You take half damage from this damage type.",
  "Origin Feat": "A special ability from your background, on top of your class features.",
  "Hit Point Die": "The die you roll for extra hit points each time you level up. Bigger die = tougher character.",
  "Hit points": "How much damage you can take. At 0 you fall unconscious and start making death saves.",
  "Armor class": "How hard you are to hit. An attack hits if its roll equals or beats your AC.",
  Initiative: "Added to your d20 roll at the start of a fight to decide who goes first.",
  Proficiency: "You're trained in it: add your proficiency bonus (+2 at level 1) to the roll.",
  Cantrips: "Spells you can cast as often as you like, without using up a spell slot.",
  "Level 1 spells": "Stronger spells that use a spell slot. You get your slots back after a long rest.",
  "Saving throws": "Rolls to resist something bad, like a spell or poison. Proficient saves get your proficiency bonus.",
  "Spell save DC": "The number an enemy must roll to resist your spells.",
  "Passive Perception": "What you notice without trying. The DM compares it to hidden things and sneaking enemies.",
};
// Ready-made characters: [label, species, lineage index, background, class, blurb]
const EX = [
  ["The healer", "Dwarf", 0, "Acolyte", "Cleric", "Tough, hard to kill and keeps the party on their feet."],
  ["The sneak", "Elf", 1, "Criminal", "Rogue", "Quick, quiet, and deals big damage from the shadows."],
  ["The tank", "Human", 0, "Soldier", "Fighter", "Heavy armor and a big sword. Simple and sturdy."],
  ["The blaster", "Tiefling", 2, "Charlatan", "Warlock", "Throws eldritch blasts and talks their way out of trouble."],
];
