// spellsData.js: spell list and spell icon lookups
const SPL = [
  [
    "Fire Bolt",
    0,
    "SW",
    "120 ft",
    "fire",
    "1d10",
    "attack",
    0,
    "Action",
    "Attack roll",
    "Instant",
    "Hurl a mote of fire; it ignites loose flammable objects.",
  ],
  [
    "Eldritch Blast",
    0,
    "L",
    "120 ft",
    "force",
    "1d10",
    "attack",
    0,
    "Action",
    "Attack roll",
    "Instant",
    "A crackling beam of force; more beams as you level.",
  ],
  [
    "Sacred Flame",
    0,
    "C",
    "60 ft",
    "radiant",
    "1d8",
    "attack",
    0,
    "Action",
    "DEX save",
    "Instant",
    "Radiance falls on a foe; cover gives no bonus.",
  ],
  [
    "Vicious Mockery",
    0,
    "B",
    "60 ft",
    "psychic",
    "1d6",
    "attack",
    0,
    "Action",
    "WIS save",
    "Instant",
    "A cutting insult hurts and weakens the target’s next attack.",
  ],
  [
    "Ray of Frost",
    0,
    "SW",
    "60 ft",
    "cold",
    "1d8",
    "control",
    0,
    "Action",
    "Attack roll",
    "Instant",
    "A frigid beam that also slows the target by 10 ft.",
  ],
  [
    "Shocking Grasp",
    0,
    "SW",
    "Touch",
    "lightning",
    "1d8",
    "attack",
    0,
    "Action",
    "Attack roll",
    "Instant",
    "Lightning leaps from your hand; the target can’t take reactions.",
  ],
  [
    "Chill Touch",
    0,
    "SLW",
    "120 ft",
    "necrotic",
    "1d10",
    "attack",
    0,
    "Action",
    "Attack roll",
    "1 round",
    "A ghostly hand that also blocks the target’s healing.",
  ],
  [
    "Poison Spray",
    0,
    "DSLW",
    "30 ft",
    "poison",
    "1d12",
    "attack",
    0,
    "Action",
    "CON save",
    "Instant",
    "A puff of toxic gas assails a creature.",
  ],
  [
    "Produce Flame",
    0,
    "D",
    "60 ft",
    "fire",
    "1d8",
    "attack",
    0,
    "Bonus",
    "Attack roll",
    "10 min",
    "Conjure a flame that lights the way or can be hurled.",
  ],
  [
    "Thorn Whip",
    0,
    "D",
    "30 ft",
    "piercing",
    "1d6",
    "control",
    0,
    "Action",
    "Attack roll",
    "Instant",
    "A vine lashes out and can pull a creature 10 ft closer.",
  ],
  [
    "Guidance",
    0,
    "CD",
    "Touch",
    "",
    "1d4",
    "support",
    1,
    "Action",
    "—",
    "1 min",
    "An ally adds 1d4 to one ability check.",
  ],
  [
    "Spare the Dying",
    0,
    "CD",
    "15 ft",
    "",
    "",
    "heal",
    0,
    "Action",
    "—",
    "Instant",
    "Stabilize a creature at 0 HP.",
  ],
  [
    "Mage Hand",
    0,
    "BLSW",
    "30 ft",
    "",
    "",
    "utility",
    0,
    "Action",
    "—",
    "1 min",
    "A spectral hand manipulates objects at a distance.",
  ],
  [
    "Prestidigitation",
    0,
    "BLSW",
    "10 ft",
    "",
    "",
    "utility",
    0,
    "Action",
    "—",
    "1 hr",
    "Minor tricks: clean, light, flavor or tiny illusions.",
  ],
  [
    "Cure Wounds",
    1,
    "BCDPR",
    "Touch",
    "",
    "2d8",
    "heal",
    0,
    "Action",
    "—",
    "Instant",
    "Heal a creature you touch; more dice at higher slots.",
  ],
  [
    "Healing Word",
    1,
    "BCD",
    "60 ft",
    "",
    "2d4",
    "heal",
    0,
    "Bonus",
    "—",
    "Instant",
    "Heal from a distance with a quick word.",
  ],
  [
    "Bless",
    1,
    "CP",
    "30 ft",
    "",
    "1d4",
    "support",
    1,
    "Action",
    "—",
    "1 min",
    "Up to three allies add 1d4 to attacks and saves.",
  ],
  [
    "Shield of Faith",
    1,
    "CP",
    "60 ft",
    "",
    "",
    "defense",
    1,
    "Bonus",
    "—",
    "10 min",
    "A shimmering field grants +2 AC to one creature.",
  ],
  [
    "Guiding Bolt",
    1,
    "C",
    "120 ft",
    "radiant",
    "4d6",
    "attack",
    0,
    "Action",
    "Attack roll",
    "1 round",
    "A flash of light; the next attack against the target has advantage.",
  ],
  [
    "Command",
    1,
    "BCP",
    "60 ft",
    "",
    "",
    "control",
    0,
    "Action",
    "WIS save",
    "1 round",
    "Utter a one-word order the target must obey.",
  ],
  [
    "Thunderwave",
    1,
    "BDSW",
    "Self",
    "thunder",
    "2d8",
    "attack",
    0,
    "Action",
    "CON save",
    "Instant",
    "A 15-ft cube of thunder damages and shoves creatures.",
  ],
  [
    "Burning Hands",
    1,
    "SW",
    "Self",
    "fire",
    "3d6",
    "attack",
    0,
    "Action",
    "DEX save",
    "Instant",
    "A 15-ft cone of flame.",
  ],
  [
    "Magic Missile",
    1,
    "SW",
    "120 ft",
    "force",
    "3d4+3",
    "attack",
    0,
    "Action",
    "Auto-hit",
    "Instant",
    "Three darts of force that never miss.",
  ],
  [
    "Shield",
    1,
    "SW",
    "Self",
    "",
    "",
    "defense",
    0,
    "Reaction",
    "—",
    "1 round",
    "+5 AC and blocks Magic Missile until your next turn.",
  ],
  [
    "Mage Armor",
    1,
    "SW",
    "Touch",
    "",
    "",
    "defense",
    0,
    "Action",
    "—",
    "8 hr",
    "Your AC becomes 13 + DEX with no armor.",
  ],
  [
    "Hex",
    1,
    "L",
    "90 ft",
    "necrotic",
    "1d6",
    "attack",
    1,
    "Bonus",
    "—",
    "1 hr",
    "Curse a target: extra necrotic damage and weakened checks.",
  ],
  [
    "Hellish Rebuke",
    1,
    "L",
    "60 ft",
    "fire",
    "2d10",
    "attack",
    0,
    "Reaction",
    "DEX save",
    "Instant",
    "Answer an attacker with a burst of hellfire.",
  ],
  [
    "Armor of Agathys",
    1,
    "L",
    "Self",
    "cold",
    "",
    "defense",
    0,
    "Action",
    "—",
    "1 hr",
    "Gain temp HP; melee attackers take cold damage.",
  ],
  [
    "Entangle",
    1,
    "D",
    "90 ft",
    "",
    "",
    "control",
    1,
    "Action",
    "STR save",
    "1 min",
    "Grasping plants restrain creatures in a 20-ft square.",
  ],
  [
    "Goodberry",
    1,
    "DR",
    "Self",
    "",
    "",
    "heal",
    0,
    "Action",
    "—",
    "Instant",
    "Berries each restore 1 HP and feed a creature for a day.",
  ],
  [
    "Hunter’s Mark",
    1,
    "R",
    "90 ft",
    "force",
    "1d6",
    "attack",
    1,
    "Bonus",
    "—",
    "1 hr",
    "Mark prey for extra damage and easy tracking.",
  ],
  [
    "Divine Favor",
    1,
    "P",
    "Self",
    "radiant",
    "1d4",
    "support",
    1,
    "Bonus",
    "—",
    "1 min",
    "Your weapon attacks deal extra radiant damage.",
  ],
  [
    "Faerie Fire",
    1,
    "BD",
    "60 ft",
    "",
    "",
    "control",
    1,
    "Action",
    "DEX save",
    "1 min",
    "Outline foes in light so attacks against them have advantage.",
  ],
  [
    "Dissonant Whispers",
    1,
    "B",
    "60 ft",
    "psychic",
    "3d6",
    "attack",
    0,
    "Action",
    "WIS save",
    "Instant",
    "A horrific whisper hurts and forces the target to flee.",
  ],
  [
    "Charm Person",
    1,
    "BDLSW",
    "30 ft",
    "",
    "",
    "control",
    0,
    "Action",
    "WIS save",
    "1 hr",
    "Make a humanoid regard you as a friendly acquaintance.",
  ],
  [
    "Detect Magic",
    1,
    "BCDPRSW",
    "Self",
    "",
    "",
    "utility",
    1,
    "Action",
    "—",
    "10 min",
    "Sense magic within 30 ft.",
  ],
];
const EL = {
    fire: "🔥",
    cold: "❄️",
    lightning: "⚡",
    acid: "🧪",
    poison: "☠️",
    necrotic: "💀",
    radiant: "☀️",
    thunder: "🌩️",
    force: "💥",
    psychic: "🔮",
    piercing: "🗡️",
  },
  TY = {
    attack: "💢",
    heal: "💚",
    support: "✨",
    defense: "🛡️",
    control: "🕸️",
    utility: "🧰",
  },
  SC = {
    Bard: ["B", 2, 4],
    Cleric: ["C", 3, 4],
    Druid: ["D", 2, 4],
    Paladin: ["P", 0, 2],
    Ranger: ["R", 0, 2],
    Sorcerer: ["S", 4, 2],
    Warlock: ["L", 2, 2],
    Wizard: ["W", 3, 6],
  },
  cap = (t) => t[0].toUpperCase() + t.slice(1);
// When each spell is worth casting
const GF = {
  "Fire Bolt": "Your go-to damage every turn from a safe distance.",
  "Eldritch Blast": "Your main attack, every single turn.",
  "Sacred Flame": "Hitting an enemy hiding behind cover.",
  "Vicious Mockery": "Weakening a big hitter's next attack while dealing a little damage.",
  "Ray of Frost": "Slowing an enemy that's chasing you or running away.",
  "Shocking Grasp": "Escaping when an enemy is next to you: it can't hit you as you leave.",
  "Chill Touch": "Fighting trolls or anything that heals itself.",
  "Poison Spray": "Big damage up close, but many monsters resist poison.",
  "Produce Flame": "A light source that doubles as a ranged attack.",
  "Thorn Whip": "Pulling an enemy into your friends' reach or off a ledge.",
  Guidance: "Before any important check: picking a lock, persuading a guard.",
  "Spare the Dying": "Stopping a downed ally's death saves when you have no healing left.",
  "Mage Hand": "Opening suspicious chests and pulling levers from a safe distance.",
  Prestidigitation: "Roleplay and small tricks: cleaning, lighting candles, flavoring food.",
  "Cure Wounds": "Big healing on an ally next to you, between or during fights.",
  "Healing Word": "Getting a downed ally back up from range, as a bonus action.",
  Bless: "The start of a hard fight: three allies hit and save more often.",
  "Shield of Faith": "Protecting the friend who's getting hit the most.",
  "Guiding Bolt": "Big damage that sets up an ally's attack with advantage.",
  Command: "Making an enemy drop its weapon, flee, or fall prone.",
  Thunderwave: "Blasting enemies that surround you and pushing them away.",
  "Burning Hands": "Groups of enemies bunched together in front of you.",
  "Magic Missile": "Finishing off a fleeing enemy or one that's hard to hit. Never misses.",
  Shield: "The moment an attack would hit you. Turns hits into misses.",
  "Mage Armor": "Cast every morning: 8 hours of better AC without wearing armor.",
  Hex: "Boosting every Eldritch Blast against one target for the whole fight.",
  "Hellish Rebuke": "Punishing whoever just hurt you, on their turn.",
  "Armor of Agathys": "Before a fight where enemies will swarm you in melee.",
  Entangle: "Stopping a group of enemies in their tracks.",
  Goodberry: "Healing between fights and never running out of food.",
  "Hunter’s Mark": "Extra damage on every hit against one target.",
  "Divine Favor": "Boosting your weapon damage for a whole fight.",
  "Faerie Fire": "Lighting up enemies so the whole party hits them more, even invisible ones.",
  "Dissonant Whispers": "Damage that also makes an enemy run, provoking free hits from allies.",
  "Charm Person": "Getting past a guard or getting information without a fight.",
  "Detect Magic": "Finding magic items and spotting enchanted traps. Can be a ritual (no slot).",
};
// Recommended picks for beginners, by spell list
const REC = {
  B: ["Vicious Mockery", "Mage Hand", "Healing Word", "Dissonant Whispers", "Faerie Fire", "Thunderwave"],
  C: ["Sacred Flame", "Guidance", "Spare the Dying", "Healing Word", "Bless", "Guiding Bolt", "Cure Wounds"],
  D: ["Produce Flame", "Guidance", "Healing Word", "Entangle", "Faerie Fire", "Goodberry"],
  P: ["Bless", "Cure Wounds"],
  R: ["Hunter’s Mark", "Cure Wounds"],
  S: ["Fire Bolt", "Ray of Frost", "Mage Hand", "Shocking Grasp", "Magic Missile", "Shield"],
  L: ["Eldritch Blast", "Mage Hand", "Hex", "Armor of Agathys"],
  W: ["Fire Bolt", "Ray of Frost", "Mage Hand", "Magic Missile", "Shield", "Mage Armor", "Thunderwave", "Detect Magic", "Burning Hands"],
};
